### ISSUE TITLE
Getting "(SystemJS) XHR error (404 Not Found)" - when trying to access the acumuli data source.

### ISSUE THREAD

**Issue by ajithka123** [akumuli/akumuli-datasource#1]
On windows, I was able to install akumuli.grafana plugin.
But getting followign error at the end.

Plugin Error
(SystemJS) XHR error (404 Not Found) loading http://789t943d:3000/public/plugins/akumuli/module.js?bust=1505838531434 Error loading http://789t943d:3000/public/plugins/akumuli/module.js

Any idea?

**Comment by ajithka123** [comment]
See the screen shot:
[Error for Git.docx](https://github.com/akumuli/akumuli.grafana/files/1315160/Error.for.Git.docx)

**Comment by Lazin** [comment]
This plugin is not ready yet. The plugin works only with specific branch of the Akumuli source code (this one https://github.com/akumuli/Akumuli/tree/search_api to be specific). I hope it will be ready to use pretty soon. Grafana support has highest priority now.

**Comment by Lazin** [comment]
Sorry if it took some of your time. I'm going to write about project state in README.md.

**Comment by ajithka123** [comment]
Thanks,
