### ISSUE TITLE
Datasource return "-not found" when there are a where clause

### ISSUE THREAD

**Issue by FragJage** [akumuli/akumuli-datasource#13]
Akumuli 0.7.54
Grafana 5.2.4

Series found without where clause :
![image](https://user-images.githubusercontent.com/6844609/46500937-57126000-c824-11e8-89de-89831a21c176.png)
(You can see there is a tag host=orangepi)

But when i add a where clause on tag host=orangepi, datasource return "-not found" :
![image](https://user-images.githubusercontent.com/6844609/46501122-da33b600-c824-11e8-8bf9-2e9269fd8fb2.png)

**Comment by Lazin** [comment]
This error indicates that there is no metric with a tag like this. At first glance, everything should work. I'm using this feature all the time. Is it possible that your series names contain some unprintable characters?
You can run this command in terminal to get all series names.

```
curl --url <replace-with-hostname>:8181/api/query -d '{ "select": "meta:names" }'
```

If it has any unprintable characters they will be shown in terminal. For instance, it can be something like `cpu_temp host=orangepi^M`.

Another approach is to use autocomplete. If you select tag key, and tag value from autocomplete they will be the same as in the database.

**Comment by FragJage** [comment]
Very nice, it's a ^M. Approach with autocomplete in Grafana does not work, but my datas are in a text file, so i have delete and recreate my database, use dos2unix on my text file and import my text file with cat file.txt >> /dev/tcp/127.0.0.1/4242.
Now it's work perfectly.
Thank you.
