### ISSUE TITLE
Invalid tag causes crash and corruption

### ISSUE THREAD

**Issue by sptrakesh** [akumuli/akumuli-datasource#21]
While testing `pivot-by-tag` via `curl` requests, I specified a non-exiting `tag` by mistake and found that Akumuli process crashed, and on restart the logs indicated data corruption.  I am running Akumuli via the 0.8.72-skylake docker image.

**Comment by Lazin** [comment]
I believe this was fixed in 0.8.73 already. Could you please check that it works?

**Comment by sptrakesh** [comment]
Yes, 0.8.73 works as expected.
